version: "3"
services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d/
  node:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      DB_HOST: mariadb
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      API_PORT: ${API_PORT}
      API_VERSION: ${API_VERSION}
      DB_PORT: ${DB_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      SHOW_ZOD_ERRORS: ${SHOW_ZOD_ERRORS}
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npm start"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      API_BASE_URL: ${API_BASE_URL}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm run dev"

volumes:
  mariadb_data:
